# Generated by Django 4.1.5 on 2023-01-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='people',
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='-', upload_to='images/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='photo',
            name='people',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
