# Generated by Django 4.1.5 on 2023-01-13 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_peopleonphoto_alter_photo_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='author',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
